version: '3.9'

services: 
  resume-web:
    image: resume-web:latest
    build:
      context: ./resume-web
      dockerfile: Dockerfile
    container_name: resume-web
    env_file: 
      - ./resume-web/.env
    ports: 
      - "8000:80"
    volumes: 
      - ./resume-web:/var/www/html
    depends_on:
      - resume-db
    networks: 
      - resume-builder-network
  
  resume-api:
    image: resume-api:latest
    build: 
      context: ./resume-api
      dockerfile: Dockerfile
    container_name: resume-api
    ports:
      - "3000:3000"
    volumes:
      - ./resume-api:/var/www/html
      - /var/www/html/node_modules # Mount node_modules only in the container and only in case local node is different than container node
    # environment:
    #   - NODE_ENV=development
    env_file: 
      - ./resume-api/.env
    networks: 
      - resume-builder-network

  resume-db: 
    # platform: linux/x86_64
    # image: mysql:5.7
    image: mongo
    container_name: resume-dbx
    #env_file:
    #  - ./resume-web/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: mtarique
      MONGO_INITDB_ROOT_PASSWORD: mt7Database
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: ${DB_DATABASE}
      #MYSQL_USER: ${DB_USERNAME}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    #  - "3306:3306"
    volumes:
      #- resume-db-data:/var/lib/mysql
      - resume-db-data:/data/db
    networks: 
      - resume-builder-network

volumes:
  resume-db-data:

networks:
  resume-builder-network:
    driver: bridge