version: '3.9'

services: 
  resume-web:
    image: resume-web:latest
    build:
      context: ./resume-web
      dockerfile: Dockerfile
    container_name: resume-web
    env_file: 
      - ./resume-web/.env
    ports: 
      - "8000:80"
    volumes: 
      - ./resume-web:/var/www/html
    depends_on:
      - resume-db
    networks: 
      - resume-builder-network
  
  resume-api:
    image: resume-api:latest
    build: 
      context: ./resume-api
      dockerfile: Dockerfile
    container_name: resume-api
    ports:
      - "3000:3000"
    volumes:
      - ./resume-api:/var/www/html
    # environment:
    #   - NODE_ENV=development
    env_file: 
      - ./resume-api/.env

  resume-db: 
    platform: linux/x86_64
    image: mysql:5.7
    container_name: resume-db
    env_file:
      - ./resume-web/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - resume-db-data:/var/lib/mysql
    networks: 
      - resume-builder-network

volumes:
  resume-db-data:

networks:
  resume-builder-network:
    driver: bridge